CREATE COLUMN TABLE USER(
	userid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email CHAR(30) NOT NULL UNIQUE, 
	firstName CHAR(30) NOT NULL,
	lastName CHAR(30) NOT NULL
);


CREATE COLUMN TABLE MOOD(
	id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	userid BIGINT NOT NULL,
	mood CHAR(100),
	energy CHAR(100),
	mindset CHAR(100),
	cravingFor CHAR(100),
	healthGoal CHAR(100),
	foodChoice CHAR(100),
	userImageUrl CHAR(200),
	FOREIGN KEY (userid) REFERENCES USER
);


INSERT INTO USER (email,firstName,lastName)
VALUES ('avinash.vaidya','Avinash','Vaidya');

INSERT INTO MOOD(userid, mood)
VALUES (1,'High')

drop table USER;

drop table MOOD;

Select * from MOOD as m where userid = (Select userid from USER as u where email = 'avinash.vaidya')

commit;